apiVersion: v1
kind: Secret
metadata:
  name: apisix-ingress-conf
  namespace: apisix
type: Opaque
stringData:
  config.yaml: |
    # log options
      log_level: "debug"
      log_output: "stderr"
      http_listen: ":8080"
      enable_profiling: true
      kubernetes:
        kubeconfig: ""
        resync_interval: "30s"
        namespace_selector:
        - "apisix.ingress=watching"
        ingress_class: "apisix"
        ingress_version: "networking/v1"
        apisix_route_version: "apisix.apache.org/v2"
        api_version: apisix.apache.org/v2
      apisix:
        default_cluster_base_url: "http://apisix-admin.apisix:9180/apisix/admin"
        default_cluster_admin_key: <input your admin key here>