apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apik3k
  namespace: apisix
spec:
  # The TLS secret that cert-manager created
  secretName: tlscert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - k3k
  commonName: api.k3k.dev
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  dnsNames:
    - "api.k3k.dev"
  issuerRef:
    name: letsencrypt-staging
    kind: Issuer
    group: cert-manager.io