apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: apisix
spec:
  acme:
    # The ACME server URL
    # Remove "-staging" when moving to production
    server: https://acme-v02-staging.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: <your-email>@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    - dns01:
        cloudflare:
          # Refer https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/
          apiTokenSecretRef:
            name: cloudflare
            key: api-token